### ISSUE TITLE
Need to know what we do about retractions

### ISSUE THREAD

**Issue by imaginator** [buddycloud/buddycloud-xep#17]
missing from section:  https://github.com/buddycloud/buddycloud-xep/blob/master/sections/60.items.xml#L6

Options tombstones: https://groups.google.com/forum/#!topic/buddycloud-dev/MpE-b2Ez254

From the old xep:

The client sends

```
<iq from="juliet@capulet.lit/bc-app" to="buddycloud.capulet.lit" type="set" id="retractitem:32"> 
  <pubsub xmlns="http://jabber.org/protocol/pubsub"> 
    <retract node="/user/juliet@capulet.lit/posts" notify="1"> 
      <item id="1291048772456"/> 
    </retract> 
  </pubsub> 
</iq>
```

Server replies

```
<iq from="buddycloud.capulet.lit" to="juliet@capulet.lit/bc-app" type="result" id="retractitem:32"/>
```

A retraction message is sent to all online clients, with an Atom tombstone to replace the deleted post

```
<message from="buddycloud.capulet.lit" id="bc:MGV3B" to="benvolio@montague.lit"> 
  <event xmlns="http://jabber.org/protocol/pubsub#event"> 
    <items node="/user/channeluser@example.com/posts"> 
      <retract id="1291048772456"/> 
      <item id="1291048772456">
        <deleted-entry xmlns="http://purl.org/atompub/tombstones/1.0" ref="xmpp:buddycloud.capulet.lit?pubsub;action=retrieve;node=/user/juliet@capulet.lit/posts;item=1291048772456" when="2012-07-01T15:08:32.950Z">
          <updated>2012-07-01T15:08:32.950Z</updated>
          <id xmlns="http://www.w3.org/2005/Atom">1291048772456</id>
          <link xmlns="http://www.w3.org/2005/Atom" href="xmpp:buddycloud.capulet.lit?pubsub;action=retrieve;node=/user/juliet@capulet.lit/posts;item=1291048772456" rel="self"/>
          <published xmlns="http://www.w3.org/2005/Atom">2012-07-01T15:08:30.922Z</published>
          <object xmlns="http://activitystrea.ms/spec/1.0/">
            <object-type>comment</object-type>
          </object>
          <verb xmlns="http://activitystrea.ms/spec/1.0/">post</verb>
        </deleted-entry>
      </item>
    </items> 
  </event> 
</message>
```

**Comment by lloydwatkin** [comment]
Currently items are just deleted and, until recently, no notification was sent out (fixed now).

I think the above is fine, but we have two questions remaining:
- What happens when a user retrieves posts?
- What happens if this is a topic parent and it has comments?

**Comment by imaginator** [comment]
My assumption was
- original post on server is replaced with tombstone.
- clients show the tombstone'd post "This post deleted" - this will keep
  the threading intact too.

Reddit handles this nicely:
http://www.reddit.com/r/askscience/comments/m8q2z/alright_science_morning_wood_why/c2z1h0k(if
you excuse the AskScience question)
ᐧ

On 17 February 2014 16:21, Lloyd Watkin notifications@github.com wrote:

> Currently items are just deleted and, until recently, no notification was
> sent out (fixed now).
> 
> I think the above is fine, but we have two questions remaining:
> - What happens when a user retrieves posts?
> - What happens if this is a topic parent and it has comments?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/buddycloud/buddycloud-xep/issues/17#issuecomment-35290681
> .

## 

Simon Tennant | buddycloud.com | +49 17 8545 0880 | office hours:
goo.gl/tQgxP

**Comment by imaginator** [comment]
Documented at http://buddycloud.com/buddycloud-xep/#items-delete
