### ISSUE TITLE
Use 'authorize' not 'authorise'

### ISSUE THREAD

**Issue by lloydwatkin** [buddycloud/buddycloud-xep#19]
We use the 'merkin spelling of 'authorise' as in XEP-0060. Therefore all correct spelling of  the word should be replaced with 'authorize' :)

**Comment by imaginator** [comment]
ACK.

**Comment by imaginator** [comment]
Fixed with https://github.com/buddycloud/buddycloud-xep/commit/3cdad280c6a017ced327f623cfa3a027f92694f4
