### ISSUE TITLE
What is a 'channel address'?

### ISSUE THREAD

**Issue by lloydwatkin** [buddycloud/buddycloud-xep#33]

**Comment by imaginator** [comment]
http://buddycloud.github.io/buddycloud-xep/#PubSub-for-humans.  Open to suggestions, otherwise closing.

**Comment by imaginator** [comment]
Fixed with https://github.com/buddycloud/buddycloud-xep/commit/c0e0a95a46f83421c33dd02588ff0f46b766ba47

**Comment by imaginator** [comment]
And closed again.
