### ISSUE TITLE
Restructure XEP

### ISSUE THREAD

**Issue by imaginator** [buddycloud/buddycloud-xep#6]
Reorganise the XEP according to the following structure:
- Introduction
  - Background
  - Glossary
- Buddycloud Server Discovery
  - disco discovery
  - DNS discovery
- Inbox operations
  - Permissions/Actors 
- Channel operations
  - Default nodes
  - Channel business logic
- Post operations
  - Firehose operations
  - Content normalization rules
  - Threading
- Follower operations
  - Follower business logic
  - Invites (see issue: https://github.com/buddycloud/buddycloud-xep/issues/4)
  - Local access model (see issue: https://github.com/buddycloud/buddycloud-xep/issues/3)

Please copy past into comments with new structure suggestions.

**Comment by lloydwatkin** [comment]
I think there should be a section of node/channel permissions/access models and `local` should be seen as a standard part of that? Unless you are simply going to talk about the differences from XEP-0060?

**Comment by abmargb** [comment]
Should search features be there too?

I think there should be a section of node/channel permissions/access models
and local should be seen as a standard part of that? Unless you are simply
going to talk about the differences from XEP-0060?

—
Reply to this email directly or view it on
GitHubhttps://github.com/buddycloud/buddycloud-xep/issues/6#issuecomment-30060972
.

**Comment by imaginator** [comment]
You are right. Thanks!

On 7 December 2013 21:56, Abmar Barros notifications@github.com wrote:

> Should search features be there too?
> 
> I think there should be a section of node/channel permissions/access
> models
> and local should be seen as a standard part of that? Unless you are simply
> going to talk about the differences from XEP-0060?
> 
> —
> Reply to this email directly or view it on
> GitHub<
> https://github.com/buddycloud/buddycloud-xep/issues/6#issuecomment-30060972>
> 
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/buddycloud/buddycloud-xep/issues/6#issuecomment-30064603
> .

## 

Simon Tennant | buddycloud.com | +49 17 8545 0880 | office hours:
goo.gl/tQgxP

**Comment by ashward** [comment]
You have been reading this I hope? http://xmpp.org/extensions/xep-0143.html ;)

**Comment by imaginator** [comment]
Much happier with the general layout now. I've got an application logic section to add but that's written already and just needs to be pulled in. Closing this issue.
