### ISSUE TITLE
Add DNS lookup details to the XEP

### ISSUE THREAD

**Issue by lloydwatkin** [buddycloud/buddycloud-xep#8]
See https://github.com/buddycloud/buddycloud-server-java/pull/114

**Comment by imaginator** [comment]
Solved with https://github.com/buddycloud/buddycloud-xep/blob/master/sections/30.discovery.xml#L86 and this issue https://github.com/buddycloud/buddycloud-server-java/issues/139 to change the server to use PTR

**Comment by lloydwatkin** [comment]
Personally I feel this should be marked as OPTIONAL.

It keeps the zealots happy, and its there as a fallback anyhow rather than the standard discovery mechanism.

**Comment by imaginator** [comment]
My reading of
https://github.com/buddycloud/buddycloud-xep/blob/master/sections/30.discovery.xml#L20makes
it sound optional/fallback-ish?

Or?
ᐧ

On 20 February 2014 09:44, Lloyd Watkin notifications@github.com wrote:

> Personally I feel this should be marked as OPTIONAL.
> 
> It keeps the zealots happy, and its there as a fallback anyhow rather than
> the standard discovery mechanism.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/buddycloud/buddycloud-xep/issues/8#issuecomment-35599273
> .

## 

Simon Tennant | buddycloud.com | +49 17 8545 0880 | office hours:
goo.gl/tQgxP
